name: Build Project
on:
  push:
    branches: [release]
  pull_request:
    branches: [release]

jobs:
  build-standalone-windows-64:
    name: Build Standalone Windows 64
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-
            
      - name: Build StandaloneWindows64
        uses: game-ci/unity-builder@v2
        id: build
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
        with:
          targetPlatform: StandaloneWindows64
          versioning: Semantic
      
      - name: Compress build
        run: zip -r ${{ steps.build.outputs.buildVersion }}.zip build/StandaloneWindows64

      - name: Clone public repo
        uses: actions/checkout@v3
        with:
          repository: WoahPieStudios/GDELECT4-ADVAPROD-BUILDS/
          path: public-builds
          token: ${{ secrets.API_TOKEN_GITHUB }}
        
      - name: Copy build to public repo
        run: cp ${{ steps.build.outputs.buildVersion }}.zip public-builds/build/StandaloneWindows64/${{ steps.build.outputs.buildVersion }}.zip

      - name: Push build to public repo
        uses: actions/checkout@v3
        with:
          repository: WoahPieStudios/GDELECT4-ADVAPROD-BUILDS/
          path: public-builds
          token: ${{ secrets.API_TOKEN_GITHUB }}
        run: |
          git config user.name bulletproofpancake
          git config user.email 57520402+bulletproofpancake@users.noreply.github.com
          git add .
          git commit -m "Update from https://github.com/${GITHUB_REPOSITORY}/commit/${GITHUB_SHA}"
          git push --force

      - name: Return License
        uses: game-ci/unity-return-license@v2
        if: always()

      - name: Notify Discord
        uses: sarisia/actions-status-discord@v1.9.0
        if: success()
        with:
          webhook: ${{secrets.DISCORD_WEBHOOK_BUILD}}
          avatar_url: "https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png"
          url: "https://woahpiestudios.github.io/gdelect4-advaprod-builds/"
