# This is a basic workflow to help you get started with Actions

name: Generate Build and Documentation

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the $default-branch branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: Build Project
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
        uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-
      
      - name: Build 
        uses: game-ci/unity-builder@v2
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
        with:
          targetPlatform: WebGL

      - name: Generate Documentation
        uses: nikeee/docfx-action@v1.0.0
        with:
          args: Documentation/docfx.json

      - name: Copy build files to docfx location
        run: sudo cp -vr build/WebGL Documentation/_site/build

      - name: Publish to Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: Documentation/_site
          force_orphan: true

      - name: Return License
        uses: game-ci/unity-return-license@v2
        if: always()

      - name: Notify Discord
        uses: sarisia/actions-status-discord@v1.9.0
        if: always()
        with:
          webhook: ${{secrets.DISCORD_WEBHOOK}}
          url: "https://woahpiestudios.github.io/GDELECT4-ADVAPROD/build/WebGL/index.html"
          avatar_url: "https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png"
