name: Build Project
on:
  push:
    branches: [main]

jobs:
  build-standalone-windows-64:
    name: Build Standalone Windows 64
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-
            
      - name: Build StandaloneWindows64
        uses: game-ci/unity-builder@v2
        id: build
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
        with:
          targetPlatform: StandaloneWindows64
          versioning: Semantic
      
      - name: Compress build
        run: zip -r ${{ steps.build.outputs.buildVersion }}.zip build/StandaloneWindows64
      
      - name: Send standalone to public repo
        uses: dmnemec/copy_file_to_another_repo_action@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source_file: '${{ steps.build.outputs.buildVersion }}.zip'
          destination_repo: 'WoahPieStudios/GDELECT4-ADVAPROD-BUILDS'
          destination_folder: 'build/StandaloneWindows64/'
          user_email: '57520402+bulletproofpancake@users.noreply.github.com'
          user_name: 'bulletproofpancake'

      - name: Return License
        uses: game-ci/unity-return-license@v2
        if: always()

      - name: Notify Discord
        uses: sarisia/actions-status-discord@v1.9.0
        if: always()
        with:
          webhook: ${{secrets.DISCORD_WEBHOOK_BUILD}}
          avatar_url: "https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png"
          url: "https://woahpiestudios.github.io/gdelect4-advaprod-builds/"
