name: Notify Discord Channel

on:
  push:
    branches: [ main ]
jobs:
  send-message:
    runs-on: windows-latest
  
    steps:
      - name: Actions Status Discord
        uses: sarisia/actions-status-discord@v1.9.0
        if: always()
        with:
          webhook: ${{secrets.DISCORD_WEBHOOK}}
          avatar_url: "https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png"
