name: Notify Discord
on:
  push:
    branches: [main]
jobs:
  notify-discord:
    name: Notify Discord
    runs-on: ubuntu-latest

    steps:
    - uses: sarisia/actions-status-discord@v1.9.0
      if: always()
      with:
        webhook: ${{secrets.DISCORD_WEBHOOK}}
        avatar_url: "https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png"